version: '3.7'

services:
  redis-db:
    container_name: redis-db
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6375:6379
    volumes:
      - redis-data:/data/redis

  flask-base-db:
    mysql5_7:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql5_7:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_NAME}
      MYSQL_DATABASE: 'fast_check_prod'
      # MYSQL_HOST: '0.0.0.0'
    ports:
      - "32000:3306"
  flask-base-service:
    container_name: flask-base-service
    build:
      context: ../flask-base-api
      dockerfile: Dockerfile
      target: prod # set the dockerfile target as debug 
    volumes:
      - '../flask-base-api:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - FLASK_DEBUG=1
      - FLASK_ENV="docker"
      - FLASK_APP=project/__init__.py
      - SECRET_KEY=${SECRET_KEY}
      - FCM_SERVER_KEY=${FCM_SERVER_KEY}
    depends_on:
      - flask-base-db
    links:
      - flask-base-db
      - redis-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask-base-service
    links:
      - flask-base-service
